### ISSUE TITLE
Returner korrekt statuskode ved ugyldig aktivitetsID

### ISSUE THREAD

**Issue by Henfau** [navikt/aktivitetsplan#395]
Handling: Kall av  '/veilarbaktivitet/api/aktivitet/:id' med en id som ikke finnes i databasen.

Forventet: 404
Faktisk: 500

_Kikker inn i speil:_
"@alexander-svendsen @alexander-svendsen @alexander-svendsen"

**Comment by alexander-svendsen** [comment]
Løst :)

**Comment by Henfau** [comment]
![image](https://user-images.githubusercontent.com/26749392/82681778-8c183400-9c4e-11ea-8d8b-63fbb0ca4a40.png)
