### ISSUE TITLE
Legg til noindex på innlogget aktivitetsplan

### ISSUE THREAD

**Issue by tobiasmcvey** [navikt/aktivitetsplan#634]
Hei

Idag dukker lenken som går direkte til innlogget aktivitetsplan opp i Google, dvs https://aktivitetsplan.nav.no/ 

Søkemotoren får ikke vist frem en informerende tittel eller beskrivelse fordi siden er innlogget. Om brukere trykker på den så blir de sendt rett til ID-porten. Det er ikke en god brukeropplevelse.

For å se dette i praksis

* Gå til google.com
* Søk på den nøyaktige URLen "https://aktivitetsplan.nav.no/"
* Om den kommer opp på topp så er siden indeksert i Google sitt søkeresultat

Ideelt sett finner brukeren deres app via en landingsside eller via en annen side når de er allerede innlogget.

Dere kan fjerne lenken fra Google og andre søkemotorer ved å legge denne kodesnutten i ```<head>``` på den innloggede siden deres. Dette er en enkel og kjapp fiks. Slik får dere også bedre styring på innganger til appen.

```<meta name="robots" content="noindex">```

Les mer her https://support.google.com/webmasters/answer/93710?hl=en

Det kan også gjøres med en HTTP header men det enkleste er HTML.

**Comment by tu55eladd** [comment]
Appen er nåes ikke uten login så hjelper ikke å legge på meta i headeren. Eneste som vil funke er å bruke header
