### ISSUE TITLE
Tilgang til API

### ISSUE THREAD

**Issue by ChristianStange** [navikt/aktivitetsplan#82]
Jeg har i løpet av innkjøringen av denne løsningen kommet med en del forslag. Ett av dem var en mobil app, og jeg ser ikke helt form meg at dette ligger i deres kjøreplan. Så jeg tenkte jeg kunne mekke sammen en. Da har jeg også ett utgangspunkt for å ta for meg de mer avanserte løsningene jeg vil ha inn.

Jeg vet i forhold til GDPR, skal jeg kunne hente ut data fra deres løsninger i ett overkommerlig format. Og jeg ser at dere ikke er kommet offentlig der enda. Men jeg lurte på om det fantes API innganger jeg kan bruke for å melke ut databasen? 

(Uansett må jeg jo finne en måte å komme rundt påloggingen på, selv om jeg har en ide for dette.)

**Comment by alexander-svendsen** [comment]
Vi takker for din henvendelse, Vi kommer tilbake med et svar 😄

**Comment by ChristianStange** [comment]
Siden jeg endelig fant en inngang til dere : Har dere fått innspillene mine ? Jeg vet han fyren skulle sende det videre til dere, og jeg ser at en av endringene jeg kom med, er implementert, men jeg får ingen tilbakemelding og den enkeltendringen kan være tilfeldig. 

Jeg gidder ikke mate inn en haug med issues denne veien, hvis forslagene allerede har blitt vurdert, valgt  og storyboardet. Ikke minst fordi det ikke gir noen effektivitetsgevisnt men kun skaper unødvendig støy. 

Men hvis dere ikke har sett sluttbrukerforslag, og ser ut som spørsmålstegn rundt innlegget mitt over, kan jeg godt mate dem inn her, bare for å uansett få tettere loop på hva dere har som overordnet målsetning, og hvordan brukerene får til å nå den.

**Comment by janeirik** [comment]
Hei
Aktivitetsplanen har responsivt design for å fungerer på mindre flater, vi har derfor ikke planer om å lage en mobil-app av løsningen.

Angående APIene, så brukes JSON som format på alle APIene, og disse er tilgjengelig om man er logget inn, men dokumentasjon for disse er per i dag ikke offentlig.

Endringer blir meldt inn til oss forløpende fra brukerstøtte og nav-kontorer, men disse er anonymisert så vi vet dessverre ikke om det er akkurat dine forslag som har havnet i innboksen våres.
Alle forslag som kommer inn blir vurdert, og prioritert.

Vi har ikke mulighet til å ta i mot endringsønsker og forslag i denne kanalen. Du finner informasjon om hvordan du kan kontakte oss på nav.no
